package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlerteApprocheAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteApprocheAllPropertiesEquals(AlerteApproche expected, AlerteApproche actual) {
        assertAlerteApprocheAutoGeneratedPropertiesEquals(expected, actual);
        assertAlerteApprocheAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteApprocheAllUpdatablePropertiesEquals(AlerteApproche expected, AlerteApproche actual) {
        assertAlerteApprocheUpdatableFieldsEquals(expected, actual);
        assertAlerteApprocheUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteApprocheAutoGeneratedPropertiesEquals(AlerteApproche expected, AlerteApproche actual) {
        assertThat(actual)
            .as("Verify AlerteApproche auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteApprocheUpdatableFieldsEquals(AlerteApproche expected, AlerteApproche actual) {
        assertThat(actual)
            .as("Verify AlerteApproche relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getSeuilDistance()).as("check seuilDistance").isEqualTo(expected.getSeuilDistance()))
            .satisfies(a -> assertThat(a.getSeuilTemps()).as("check seuilTemps").isEqualTo(expected.getSeuilTemps()))
            .satisfies(a -> assertThat(a.getTypeSeuil()).as("check typeSeuil").isEqualTo(expected.getTypeSeuil()))
            .satisfies(a -> assertThat(a.getJoursActivation()).as("check joursActivation").isEqualTo(expected.getJoursActivation()))
            .satisfies(a -> assertThat(a.getHeureDebut()).as("check heureDebut").isEqualTo(expected.getHeureDebut()))
            .satisfies(a -> assertThat(a.getHeureFin()).as("check heureFin").isEqualTo(expected.getHeureFin()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateCreation()).as("check dateCreation").isEqualTo(expected.getDateCreation()))
            .satisfies(a -> assertThat(a.getDateModification()).as("check dateModification").isEqualTo(expected.getDateModification()))
            .satisfies(a ->
                assertThat(a.getDernierDeclenchement()).as("check dernierDeclenchement").isEqualTo(expected.getDernierDeclenchement())
            )
            .satisfies(a ->
                assertThat(a.getNombreDeclenchements()).as("check nombreDeclenchements").isEqualTo(expected.getNombreDeclenchements())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteApprocheUpdatableRelationshipsEquals(AlerteApproche expected, AlerteApproche actual) {
        assertThat(actual)
            .as("Verify AlerteApproche relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
