package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlerteLigneArretAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteLigneArretAllPropertiesEquals(AlerteLigneArret expected, AlerteLigneArret actual) {
        assertAlerteLigneArretAutoGeneratedPropertiesEquals(expected, actual);
        assertAlerteLigneArretAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteLigneArretAllUpdatablePropertiesEquals(AlerteLigneArret expected, AlerteLigneArret actual) {
        assertAlerteLigneArretUpdatableFieldsEquals(expected, actual);
        assertAlerteLigneArretUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteLigneArretAutoGeneratedPropertiesEquals(AlerteLigneArret expected, AlerteLigneArret actual) {
        assertThat(actual)
            .as("Verify AlerteLigneArret auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteLigneArretUpdatableFieldsEquals(AlerteLigneArret expected, AlerteLigneArret actual) {
        assertThat(actual)
            .as("Verify AlerteLigneArret relevant properties")
            .satisfies(a -> assertThat(a.getSens()).as("check sens").isEqualTo(expected.getSens()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteLigneArretUpdatableRelationshipsEquals(AlerteLigneArret expected, AlerteLigneArret actual) {
        assertThat(actual)
            .as("Verify AlerteLigneArret relationships")
            .satisfies(a -> assertThat(a.getLigne()).as("check ligne").isEqualTo(expected.getLigne()))
            .satisfies(a -> assertThat(a.getArret()).as("check arret").isEqualTo(expected.getArret()))
            .satisfies(a -> assertThat(a.getAlerteApproche()).as("check alerteApproche").isEqualTo(expected.getAlerteApproche()));
    }
}
