package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlerteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteAllPropertiesEquals(Alerte expected, Alerte actual) {
        assertAlerteAutoGeneratedPropertiesEquals(expected, actual);
        assertAlerteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteAllUpdatablePropertiesEquals(Alerte expected, Alerte actual) {
        assertAlerteUpdatableFieldsEquals(expected, actual);
        assertAlerteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteAutoGeneratedPropertiesEquals(Alerte expected, Alerte actual) {
        assertThat(actual)
            .as("Verify Alerte auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteUpdatableFieldsEquals(Alerte expected, Alerte actual) {
        assertThat(actual)
            .as("Verify Alerte relevant properties")
            .satisfies(a -> assertThat(a.getTypeCible()).as("check typeCible").isEqualTo(expected.getTypeCible()))
            .satisfies(a -> assertThat(a.getCibleId()).as("check cibleId").isEqualTo(expected.getCibleId()))
            .satisfies(a -> assertThat(a.getSeuilMinutes()).as("check seuilMinutes").isEqualTo(expected.getSeuilMinutes()))
            .satisfies(a -> assertThat(a.getJoursActivation()).as("check joursActivation").isEqualTo(expected.getJoursActivation()))
            .satisfies(a -> assertThat(a.getHeureDebut()).as("check heureDebut").isEqualTo(expected.getHeureDebut()))
            .satisfies(a -> assertThat(a.getHeureFin()).as("check heureFin").isEqualTo(expected.getHeureFin()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a ->
                assertThat(a.getDernierDeclenchement()).as("check dernierDeclenchement").isEqualTo(expected.getDernierDeclenchement())
            )
            .satisfies(a ->
                assertThat(a.getNombreDeclenchements()).as("check nombreDeclenchements").isEqualTo(expected.getNombreDeclenchements())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlerteUpdatableRelationshipsEquals(Alerte expected, Alerte actual) {
        assertThat(actual)
            .as("Verify Alerte relationships")
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
