package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.yegg.app.domain.AssertUtils.bigDecimalCompareTo;

public class ArretAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArretAllPropertiesEquals(Arret expected, Arret actual) {
        assertArretAutoGeneratedPropertiesEquals(expected, actual);
        assertArretAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArretAllUpdatablePropertiesEquals(Arret expected, Arret actual) {
        assertArretUpdatableFieldsEquals(expected, actual);
        assertArretUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArretAutoGeneratedPropertiesEquals(Arret expected, Arret actual) {
        assertThat(actual)
            .as("Verify Arret auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArretUpdatableFieldsEquals(Arret expected, Arret actual) {
        assertThat(actual)
            .as("Verify Arret relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a ->
                assertThat(a.getLatitude()).as("check latitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLatitude())
            )
            .satisfies(a ->
                assertThat(a.getLongitude()).as("check longitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLongitude())
            )
            .satisfies(a -> assertThat(a.getAltitude()).as("check altitude").isEqualTo(expected.getAltitude()))
            .satisfies(a -> assertThat(a.getAdresse()).as("check adresse").isEqualTo(expected.getAdresse()))
            .satisfies(a -> assertThat(a.getVille()).as("check ville").isEqualTo(expected.getVille()))
            .satisfies(a -> assertThat(a.getCodePostal()).as("check codePostal").isEqualTo(expected.getCodePostal()))
            .satisfies(a -> assertThat(a.getZoneTarifaire()).as("check zoneTarifaire").isEqualTo(expected.getZoneTarifaire()))
            .satisfies(a -> assertThat(a.getEquipements()).as("check equipements").isEqualTo(expected.getEquipements()))
            .satisfies(a -> assertThat(a.getPhoto()).as("check photo").isEqualTo(expected.getPhoto()))
            .satisfies(a -> assertThat(a.getPhotoContentType()).as("check photo contenty type").isEqualTo(expected.getPhotoContentType()))
            .satisfies(a -> assertThat(a.getAccessiblePMR()).as("check accessiblePMR").isEqualTo(expected.getAccessiblePMR()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArretUpdatableRelationshipsEquals(Arret expected, Arret actual) {
        // empty method
    }
}
