package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.yegg.app.domain.AssertUtils.bigDecimalCompareTo;

public class BusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusAllPropertiesEquals(Bus expected, Bus actual) {
        assertBusAutoGeneratedPropertiesEquals(expected, actual);
        assertBusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusAllUpdatablePropertiesEquals(Bus expected, Bus actual) {
        assertBusUpdatableFieldsEquals(expected, actual);
        assertBusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusAutoGeneratedPropertiesEquals(Bus expected, Bus actual) {
        assertThat(actual)
            .as("Verify Bus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusUpdatableFieldsEquals(Bus expected, Bus actual) {
        assertThat(actual)
            .as("Verify Bus relevant properties")
            .satisfies(a -> assertThat(a.getNumeroVehicule()).as("check numeroVehicule").isEqualTo(expected.getNumeroVehicule()))
            .satisfies(a -> assertThat(a.getPlaque()).as("check plaque").isEqualTo(expected.getPlaque()))
            .satisfies(a -> assertThat(a.getModele()).as("check modele").isEqualTo(expected.getModele()))
            .satisfies(a -> assertThat(a.getConstructeur()).as("check constructeur").isEqualTo(expected.getConstructeur()))
            .satisfies(a -> assertThat(a.getCapacite()).as("check capacite").isEqualTo(expected.getCapacite()))
            .satisfies(a -> assertThat(a.getCapaciteDebout()).as("check capaciteDebout").isEqualTo(expected.getCapaciteDebout()))
            .satisfies(a -> assertThat(a.getAnneeFabrication()).as("check anneeFabrication").isEqualTo(expected.getAnneeFabrication()))
            .satisfies(a -> assertThat(a.getEnergie()).as("check energie").isEqualTo(expected.getEnergie()))
            .satisfies(a -> assertThat(a.getAutonomieKm()).as("check autonomieKm").isEqualTo(expected.getAutonomieKm()))
            .satisfies(a -> assertThat(a.getGpsDeviceId()).as("check gpsDeviceId").isEqualTo(expected.getGpsDeviceId()))
            .satisfies(a -> assertThat(a.getGpsStatus()).as("check gpsStatus").isEqualTo(expected.getGpsStatus()))
            .satisfies(a -> assertThat(a.getGpsLastPing()).as("check gpsLastPing").isEqualTo(expected.getGpsLastPing()))
            .satisfies(a -> assertThat(a.getGpsBatteryLevel()).as("check gpsBatteryLevel").isEqualTo(expected.getGpsBatteryLevel()))
            .satisfies(a ->
                assertThat(a.getCurrentLatitude())
                    .as("check currentLatitude")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentLatitude())
            )
            .satisfies(a ->
                assertThat(a.getCurrentLongitude())
                    .as("check currentLongitude")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentLongitude())
            )
            .satisfies(a ->
                assertThat(a.getCurrentVitesse())
                    .as("check currentVitesse")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCurrentVitesse())
            )
            .satisfies(a -> assertThat(a.getCurrentCap()).as("check currentCap").isEqualTo(expected.getCurrentCap()))
            .satisfies(a -> assertThat(a.getPositionUpdatedAt()).as("check positionUpdatedAt").isEqualTo(expected.getPositionUpdatedAt()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getDateMiseEnService()).as("check dateMiseEnService").isEqualTo(expected.getDateMiseEnService()))
            .satisfies(a ->
                assertThat(a.getDateDernierEntretien()).as("check dateDernierEntretien").isEqualTo(expected.getDateDernierEntretien())
            )
            .satisfies(a ->
                assertThat(a.getProchainEntretienKm()).as("check prochainEntretienKm").isEqualTo(expected.getProchainEntretienKm())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBusUpdatableRelationshipsEquals(Bus expected, Bus actual) {
        assertThat(actual)
            .as("Verify Bus relationships")
            .satisfies(a -> assertThat(a.getLigne()).as("check ligne").isEqualTo(expected.getLigne()))
            .satisfies(a -> assertThat(a.getChauffeur()).as("check chauffeur").isEqualTo(expected.getChauffeur()));
    }
}
