package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HistoriqueAlerteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAlerteAllPropertiesEquals(HistoriqueAlerte expected, HistoriqueAlerte actual) {
        assertHistoriqueAlerteAutoGeneratedPropertiesEquals(expected, actual);
        assertHistoriqueAlerteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAlerteAllUpdatablePropertiesEquals(HistoriqueAlerte expected, HistoriqueAlerte actual) {
        assertHistoriqueAlerteUpdatableFieldsEquals(expected, actual);
        assertHistoriqueAlerteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAlerteAutoGeneratedPropertiesEquals(HistoriqueAlerte expected, HistoriqueAlerte actual) {
        assertThat(actual)
            .as("Verify HistoriqueAlerte auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAlerteUpdatableFieldsEquals(HistoriqueAlerte expected, HistoriqueAlerte actual) {
        assertThat(actual)
            .as("Verify HistoriqueAlerte relevant properties")
            .satisfies(a -> assertThat(a.getDateDeclenchement()).as("check dateDeclenchement").isEqualTo(expected.getDateDeclenchement()))
            .satisfies(a -> assertThat(a.getBusNumero()).as("check busNumero").isEqualTo(expected.getBusNumero()))
            .satisfies(a -> assertThat(a.getDistanceReelle()).as("check distanceReelle").isEqualTo(expected.getDistanceReelle()))
            .satisfies(a -> assertThat(a.getTempsReel()).as("check tempsReel").isEqualTo(expected.getTempsReel()))
            .satisfies(a -> assertThat(a.getTypeDeclenchement()).as("check typeDeclenchement").isEqualTo(expected.getTypeDeclenchement()))
            .satisfies(a ->
                assertThat(a.getNotificationEnvoyee()).as("check notificationEnvoyee").isEqualTo(expected.getNotificationEnvoyee())
            )
            .satisfies(a -> assertThat(a.getDateLecture()).as("check dateLecture").isEqualTo(expected.getDateLecture()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHistoriqueAlerteUpdatableRelationshipsEquals(HistoriqueAlerte expected, HistoriqueAlerte actual) {
        assertThat(actual)
            .as("Verify HistoriqueAlerte relationships")
            .satisfies(a -> assertThat(a.getBus()).as("check bus").isEqualTo(expected.getBus()))
            .satisfies(a -> assertThat(a.getAlerteApproche()).as("check alerteApproche").isEqualTo(expected.getAlerteApproche()))
            .satisfies(a -> assertThat(a.getUtilisateur()).as("check utilisateur").isEqualTo(expected.getUtilisateur()));
    }
}
