package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.yegg.app.domain.AssertUtils.bigDecimalCompareTo;

public class LigneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneAllPropertiesEquals(Ligne expected, Ligne actual) {
        assertLigneAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneAllUpdatablePropertiesEquals(Ligne expected, Ligne actual) {
        assertLigneUpdatableFieldsEquals(expected, actual);
        assertLigneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneAutoGeneratedPropertiesEquals(Ligne expected, Ligne actual) {
        assertThat(actual)
            .as("Verify Ligne auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneUpdatableFieldsEquals(Ligne expected, Ligne actual) {
        assertThat(actual)
            .as("Verify Ligne relevant properties")
            .satisfies(a -> assertThat(a.getNumero()).as("check numero").isEqualTo(expected.getNumero()))
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getDirection()).as("check direction").isEqualTo(expected.getDirection()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCouleur()).as("check couleur").isEqualTo(expected.getCouleur()))
            .satisfies(a ->
                assertThat(a.getDistanceKm())
                    .as("check distanceKm")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDistanceKm())
            )
            .satisfies(a -> assertThat(a.getDureeMoyenne()).as("check dureeMoyenne").isEqualTo(expected.getDureeMoyenne()))
            .satisfies(a -> assertThat(a.getFrequence()).as("check frequence").isEqualTo(expected.getFrequence()))
            .satisfies(a -> assertThat(a.getStatut()).as("check statut").isEqualTo(expected.getStatut()))
            .satisfies(a -> assertThat(a.getJoursFeries()).as("check joursFeries").isEqualTo(expected.getJoursFeries()))
            .satisfies(a -> assertThat(a.getDateDebut()).as("check dateDebut").isEqualTo(expected.getDateDebut()))
            .satisfies(a -> assertThat(a.getDateFin()).as("check dateFin").isEqualTo(expected.getDateFin()))
            .satisfies(a -> assertThat(a.getActif()).as("check actif").isEqualTo(expected.getActif()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneUpdatableRelationshipsEquals(Ligne expected, Ligne actual) {
        assertThat(actual)
            .as("Verify Ligne relationships")
            .satisfies(a -> assertThat(a.getOperateur()).as("check operateur").isEqualTo(expected.getOperateur()));
    }
}
