package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.yegg.app.domain.AssertUtils.bigDecimalCompareTo;

public class LigneArretAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneArretAllPropertiesEquals(LigneArret expected, LigneArret actual) {
        assertLigneArretAutoGeneratedPropertiesEquals(expected, actual);
        assertLigneArretAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneArretAllUpdatablePropertiesEquals(LigneArret expected, LigneArret actual) {
        assertLigneArretUpdatableFieldsEquals(expected, actual);
        assertLigneArretUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneArretAutoGeneratedPropertiesEquals(LigneArret expected, LigneArret actual) {
        assertThat(actual)
            .as("Verify LigneArret auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneArretUpdatableFieldsEquals(LigneArret expected, LigneArret actual) {
        assertThat(actual)
            .as("Verify LigneArret relevant properties")
            .satisfies(a -> assertThat(a.getOrdre()).as("check ordre").isEqualTo(expected.getOrdre()))
            .satisfies(a -> assertThat(a.getTempsTrajetDepart()).as("check tempsTrajetDepart").isEqualTo(expected.getTempsTrajetDepart()))
            .satisfies(a ->
                assertThat(a.getDistanceDepart())
                    .as("check distanceDepart")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDistanceDepart())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLigneArretUpdatableRelationshipsEquals(LigneArret expected, LigneArret actual) {
        assertThat(actual)
            .as("Verify LigneArret relationships")
            .satisfies(a -> assertThat(a.getLigne()).as("check ligne").isEqualTo(expected.getLigne()))
            .satisfies(a -> assertThat(a.getArret()).as("check arret").isEqualTo(expected.getArret()));
    }
}
