package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RapportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportAllPropertiesEquals(Rapport expected, Rapport actual) {
        assertRapportAutoGeneratedPropertiesEquals(expected, actual);
        assertRapportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportAllUpdatablePropertiesEquals(Rapport expected, Rapport actual) {
        assertRapportUpdatableFieldsEquals(expected, actual);
        assertRapportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportAutoGeneratedPropertiesEquals(Rapport expected, Rapport actual) {
        assertThat(actual)
            .as("Verify Rapport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportUpdatableFieldsEquals(Rapport expected, Rapport actual) {
        assertThat(actual)
            .as("Verify Rapport relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPeriodeDebut()).as("check periodeDebut").isEqualTo(expected.getPeriodeDebut()))
            .satisfies(a -> assertThat(a.getPeriodeFin()).as("check periodeFin").isEqualTo(expected.getPeriodeFin()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getContenu()).as("check contenu").isEqualTo(expected.getContenu()))
            .satisfies(a -> assertThat(a.getDateGeneration()).as("check dateGeneration").isEqualTo(expected.getDateGeneration()))
            .satisfies(a -> assertThat(a.getGenerePar()).as("check generePar").isEqualTo(expected.getGenerePar()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRapportUpdatableRelationshipsEquals(Rapport expected, Rapport actual) {
        assertThat(actual)
            .as("Verify Rapport relationships")
            .satisfies(a -> assertThat(a.getOperateur()).as("check operateur").isEqualTo(expected.getOperateur()))
            .satisfies(a -> assertThat(a.getAdmin()).as("check admin").isEqualTo(expected.getAdmin()));
    }
}
