package sn.yegg.app.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.yegg.app.domain.AssertUtils.bigDecimalCompareTo;

public class TrackingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingAllPropertiesEquals(Tracking expected, Tracking actual) {
        assertTrackingAutoGeneratedPropertiesEquals(expected, actual);
        assertTrackingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingAllUpdatablePropertiesEquals(Tracking expected, Tracking actual) {
        assertTrackingUpdatableFieldsEquals(expected, actual);
        assertTrackingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingAutoGeneratedPropertiesEquals(Tracking expected, Tracking actual) {
        assertThat(actual)
            .as("Verify Tracking auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingUpdatableFieldsEquals(Tracking expected, Tracking actual) {
        assertThat(actual)
            .as("Verify Tracking relevant properties")
            .satisfies(a ->
                assertThat(a.getLatitude()).as("check latitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLatitude())
            )
            .satisfies(a ->
                assertThat(a.getLongitude()).as("check longitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLongitude())
            )
            .satisfies(a ->
                assertThat(a.getVitesse()).as("check vitesse").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getVitesse())
            )
            .satisfies(a -> assertThat(a.getCap()).as("check cap").isEqualTo(expected.getCap()))
            .satisfies(a -> assertThat(a.getPrecision()).as("check precision").isEqualTo(expected.getPrecision()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()))
            .satisfies(a -> assertThat(a.getSource()).as("check source").isEqualTo(expected.getSource()))
            .satisfies(a -> assertThat(a.getEvenement()).as("check evenement").isEqualTo(expected.getEvenement()))
            .satisfies(a -> assertThat(a.getCommentaire()).as("check commentaire").isEqualTo(expected.getCommentaire()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTrackingUpdatableRelationshipsEquals(Tracking expected, Tracking actual) {
        assertThat(actual)
            .as("Verify Tracking relationships")
            .satisfies(a -> assertThat(a.getBus()).as("check bus").isEqualTo(expected.getBus()));
    }
}
